### ISSUE TITLE
PUT Request Doesn't Seem to be Working on Localhost

### ISSUE THREAD

**Issue by tramel-woodard** [hamzaali00001/laravel-passport-authentication#1]
Hello @hamzaali00001,

When coding out your laravel-passport example for version 5.6 from the original article:

[Create REST API with Authentication](https://tutsforweb.com/laravel-passport-create-rest-api-with-authentication/)

The PUT request submits correctly via Postman, however when sending the GET request for /api/products, the change has not resolved.

Also, checked database and change has not resolved. Here is the code for ProductController:

    public function update(Request $request, $id)
        {
            $product = auth()->user()->products()->find($id);
 
        if (!$product) {
            return response()->json([
                'success' => false,
                'message' => 'Product with id ' . $id . ' not found'
            ], 400);
        }
 
        $updated = $product->fill($request->all())->save();
 
        if ($updated)
            return response()->json([
                'success' => true
            ]);
        else
            return response()->json([
                'success' => false,
                'message' => 'Product could not be updated'
            ], 500);
    }

Please note that the GET /api/products and POST /api/products work just fine and new products can be successfully posted to the DB.

Please advise.

**Comment by tramel-woodard** [comment]
@hamzaali00001 

I've actually found the issue. In your screen capture for the PUT: /api/products/{id} request:

[Photo for: Product Update API](https://tutsforweb.com/wp-content/uploads/2018/05/update.png)

The selected format is **form-data**. However, it seems it should be **x-www-form-urlencoded**.

Not sure if anyone else was having an issue with that, but you could possibly edit the source image or add a note at your article.

Great repo. Thanks again!

**Comment by afiq90** [comment]
I also have this same problem, yeah it's working with **x-www-form-urlencoded**, can i know why it does not working with form-data? Thanks in advance.
